theme: minima
plugins:
- jekyll-remote-theme
- jekyll-paginate
title: Achtelik.it
description: Thoughts of a software engineer.
timezone: Europe/Berlin
paginate: 10
paginate_path: "/:num/"
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      excerpt_separator: <!--more-->
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
minima:
  date_format: "%Y-%m-%d %H:%M"
show_excerpts: true
header_pages:
  - _pages/topics.md
  - _pages/projects.md
  - _pages/about.md
  - _pages/search.html
include:
  - _pages
tipue_search:
  exclude:
    files: [index.html, _pages/search.html]