remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-paginate
title: Achtelik.it
description: Thoughts of a software engineer.
timezone: Europe/Berlin
paginate: 1
paginate_path: "/blog/page:num/"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      excerpt_separator: <!--more-->
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
