remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Achtelik.it
description: Thoughts of a software engineer.
timezone: Europe/Berlin
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts
    values:
      layout: "post"
